name: Java Build
on:
   push:
      branches:
      - master
   pull_request:
      types:
      - opened
      - synchronize
      - reopened
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  name: Checkout project
         uses: actions/checkout@v4
         with:
            fetch-depth: 0
      -  name: Set up JDK
         uses: actions/setup-java@v2
         with:
            java-version: 11
            distribution: adopt
      -  name: Cache SonarCloud packages
         uses: actions/cache@v3
         with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      -  name: Build with Maven on Java 11
         run: mvn -B clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            LOGDNA_INGEST_KEY: ${{ secrets.LOGDNA_INGEST_KEY }}
            LOGDNA_INGEST_URL: ${{ secrets.LOGDNA_INGEST_URL }}