name: Maven Release & Deploy
on: workflow_dispatch
jobs:
   release:
      runs-on: ubuntu-latest
      steps:
      -  name: Checkout project
         uses: actions/checkout@v2
      -  name: Set up JDK with Maven Central Repository
         uses: actions/setup-java@v1
         with:
            java-version: 11
      -  name: Release & Deploy
         uses: qcastel/github-actions-maven-release@master
         with:
            release-branch-name: master
            gpg-enabled: true
            gpg-key-id: ${{secrets.RELEASE_GPG_KEY_ID}}
            gpg-key: ${{secrets.RELEASE_GPG_KEY}}
            git-release-bot-name: ${{secrets.RELEASE_USER_NAME}}
            git-release-bot-email: ${{secrets.RELEASE_USER_EMAIL}}
            access-token: ${{secrets.RELEASE_GITHUB_TOKEN}}
            maven-repo-server-id: ossrh
            maven-repo-server-username: ${{secrets.OSSRH_USERNAME}}
            maven-repo-server-password: ${{secrets.OSSRH_PASSWORD}}
            maven-args: -Prelease -DskipTests -Dgpg.keyname=${{secrets.RELEASE_GPG_KEY_ID}} -Dgpg.passphrase=
      -  name: Deploy to GitHub Pages
         if: success()
         uses: crazy-max/ghaction-github-pages@v2
         with:
            target_branch: gh-pages
            build_dir: target/generated-docs
         env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}